name: "Download Dropbox Folder"
description: "Download data from a dropbox folder"
author: "Talley Lambert"
inputs:
  dropbox-token:
    description: "Dropbox Access Token"
    required: true
  source-path:
    description: "The path of the folder to download from Dropbox"
    required: true
  dest-path:
    description: "The path where the downloaded folder will be placed"
    required: true
    default: "dropbox-artifacts"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "download"
  color: "blue"
