name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dropbox-token: ${{ secrets.DROPBOX_TOKEN }}
          source-path: "/nd2_test_data/1_noadd_020.nd2"
          dest-path: "some/folder"

      # confirm that we wrote the file
      - run: tree
      - run: |
          if [[ -f "some/folder/1_noadd_020.nd2" ]]; then
              echo "File exists."
          else
              echo "File does not exist.";
              exit 1;
          fi
